### ISSUE TITLE
Рефакторинг Тир-0

### ISSUE THREAD

**Issue by Euhcslel** [HARLEQU1IN/dungeon#1]
- [ ] #2
Пример: ([ссылка](https://github.com/Be3y4uu-K0T/test-dungeon/blob/a631bc9b2c8c4285671685034e8ac93fcbf61682/rustfmt.toml))
```toml
condense_wildcard_suffixes = true
error_on_line_overflow = true
style_edition = "2024"
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "One"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
```
- [ ] #3
Пример ([ссылка](https://github.com/Be3y4uu-K0T/test-dungeon/blob/a631bc9b2c8c4285671685034e8ac93fcbf61682/Cargo.toml))
```toml
[package]
name = "test-dungeon"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
split-debuginfo = "off"
strip = true
```
- [ ] #4
Пример ([ссылка](https://github.com/Be3y4uu-K0T/test-dungeon/blob/a631bc9b2c8c4285671685034e8ac93fcbf61682/.gitignore))
```gitignore
## Editor
.vscode/
.vs/
.zed/

## Build
build/
dist/
debug/
target/

## Temporary files
.DS_Store
*~
\#*
\#*\#
.#*

## Tags
tags
tags.*
TAGS
TAGS.*

## direnv
.env
.envrc
.direnv/

# These are backup files generated by rustfmt
**/*.rs.bk
```
- [ ] #5
Пример ([ссылка](https://github.com/Be3y4uu-K0T/test-dungeon/blob/a631bc9b2c8c4285671685034e8ac93fcbf61682/.gitattributes))
```gitattributes
[attr]rust text eol=lf whitespace=space-in-indent,trailing-space,tabwidth=4

* text=auto eol=lf
*.rs rust diff=rust
Cargo.lock linguist-generated=true
```
- [ ] #6
Пример ([ссылка](https://github.com/Be3y4uu-K0T/test-dungeon/blob/a631bc9b2c8c4285671685034e8ac93fcbf61682/.editorconfig))
```editorconfig
root = true

[*]
charset = utf-8
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 4

[*.rs]
max_line_length = 80

[*.yml]
indent_size = 2
```
- [ ] #7
Пример ([ссылка](https://github.com/Be3y4uu-K0T/test-dungeon/blob/a631bc9b2c8c4285671685034e8ac93fcbf61682/.github/workflows/rust.yml))
```yml
name: Rust

on:
  push:
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Cargo check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo check
        run: cargo check --verbose --release

  fmt:
    name: Cargo fmt
    needs: check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Cargo fmt
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: Cargo clippy
    needs: check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - name: Cargo clippy
        run: cargo +nightly clippy --verbose --release

  build:
    name: Cargo build
    needs: [fmt, clippy]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo build
        run: cargo build --verbose --release

  test:
    name: Cargo build
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo test
        run: cargo test --verbose --release
```
- [ ] #8
```json
{
    "[rust]": {
        "editor.defaultFormatter": "rust-lang.rust-analyzer",
        "editor.formatOnSave": true
    },
    "rust-analyzer.rustfmt.extraArgs": [
        "+nightly"
    ],
    "editor.defaultFormatter": "EditorConfig.EditorConfig",
    "editor.formatOnSave": true
}
```
